# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [11]:
# Import torch
import torch

# Create random tensor
shape = torch.rand((7,7),dtype=torch.float32)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [25]:
# Create another random tensor
shap_2 = torch.rand((1,7),dtype=torch.float32)
# Perform matrix multiplication
multiplication = torch.matmul(shape, shap_2.T)
print(multiplication,multiplication.shape)

tensor([[1.3115],
        [1.4162],
        [1.2360],
        [1.2268],
        [1.2441],
        [1.4003],
        [1.1873]]) torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [26]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
shap_3 = torch.rand((7, 7), dtype=torch.float32)
shap_4 = torch.rand((1, 7), dtype=torch.float32)

# Matrix multiply tensors
multiplication_2 = torch.matmul(shap_3, shap_4.T)
print(multiplication, multiplication.shape)

tensor([[1.3115],
        [1.4162],
        [1.2360],
        [1.2268],
        [1.2441],
        [1.4003],
        [1.1873]]) torch.Size([7, 1])


In [27]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
shap_3 = torch.rand((7, 7), dtype=torch.float32)
shap_4 = torch.rand((1, 7), dtype=torch.float32)

# Matrix multiply tensors
multiplication_2 = torch.matmul(shap_3, shap_4.T)
print(multiplication, multiplication.shape)

# حضرتك (: كمل

tensor([[1.3115],
        [1.4162],
        [1.2360],
        [1.2268],
        [1.2441],
        [1.4003],
        [1.1873]]) torch.Size([7, 1])



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [29]:
!nvidia-smi

Sun Oct 19 22:56:02 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [31]:
import torch
torch.cuda.is_available()

True

In [35]:
# Set random seed

torch.manual_seed(1234)

# Check for access to GPU

if torch.cuda.is_available():
    device = "cuda"
else:
    print("GPU not available on this device.")


# Create two random tensors on GPU
tensor_1 = torch.rand((4, 4))
tensor_2 = torch.rand((4, 4))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [39]:
# Perform matmul on tensor_A and tensor_B
matmul = torch.matmul(tensor_1, tensor_2)
print(matmul, matmul.device)
tensor_on_gpu = matmul.to(device)
tensor_on_gpu

tensor([[0.7885, 0.3895, 0.4709, 0.5203],
        [0.8550, 0.3612, 0.5277, 0.6647],
        [1.5894, 1.2092, 0.9745, 1.2624],
        [1.5178, 1.0693, 0.9744, 1.4440]]) cpu


tensor([[0.7885, 0.3895, 0.4709, 0.5203],
        [0.8550, 0.3612, 0.5277, 0.6647],
        [1.5894, 1.2092, 0.9745, 1.2624],
        [1.5178, 1.0693, 0.9744, 1.4440]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [44]:
# Find max
print(torch.max(matmul))
# Find min
torch.min(matmul)


tensor(1.5894)


tensor(0.3612)

### 9. Find the maximum and minimum index values of the output of 7.

In [47]:
# Find arg max
print(matmul.argmax())
# Find arg min
matmul.argmin()

tensor(8)


tensor(5)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [49]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_a = torch.rand((1, 1, 1, 10))

# Remove single dimensions
tensor_b = tensor_a.squeeze()

# Print out tensors and their shapes
print(tensor_a, tensor_a.shape)
print(tensor_b, tensor_b.shape)



tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
